# Experimental
# Currently ineffective
# Goal is to provide centralized location for user-defined configuration parameters
# toml used because now standard package in python.
#
# this is a all lowercase structured version file
#
[lights]
distance_between_green_lights = 20  # meters, distance between taxiway lights on ground
distance_between_lights = 40  # meters, distance between lights on ground when showing all taxiways. This can build numerous lights so keep them far apart!

[light_type]
green.name="custom_green.obj"
green.color=[0, 1, 0]
green.size=20
green.intensity=20
green.texture=3

# alternate toml writing:
[light_type.red]
name="custom_red.obj"
color=[0, 1, 0]
size=20
intensity=20
texture=3

[rabbit]
lights_ahead = 0  # Number of lights in front of rabbit. If 0, lights all lights up to next stopbar or destination.
rabbit_length = 10  # number of lights that blink in front of aircraft
rabbit_duration = 0.2  # secs duration of "off" light in rabbit, also determine the rabbit speed

[xplane]
# While FtG is running for your, dim the airport lights to level "off", "lo", "med", or "hi". Other values are ignored.
runway_light_level_while_ftg = "off" # "off", "lo", "med", or "hi"
