# Experimental
# Currently ineffective
# Goal is to provide centralized location for user-defined configuration parameters
# toml used because now standard package in python.
#
DISTANCE_BETWEEN_GREEN_LIGHTS = 20  # meters, distance between taxiway lights on ground
DISTANCE_BETWEEN_LIGHTS = 40  # meters, distance between lights on ground when showing all taxiways. This can build numerous lights so keep them far apart!

LIGHTS_AHEAD = 0  # Number of lights in front of rabbit. If 0, lights all lights up to next stopbar or destination.
RABBIT_LENGTH = 10  # number of lights that blink in front of aircraft
RABBIT_DURATION = 0.2  # secs duration of "off" light in rabbit, also determine the rabbit speed

# While FtG is running for your, dim the airport lights to level "off", "lo", "med", or "hi". Other values are ignored.
RUNWAY_LIGHT_LEVEL_WHILE_FTG = "off" # "off", "lo", "med", or "hi"
