# Experimental
# Currently ineffective
# Goal is to provide centralized location for user-defined configuration parameters
# toml used because now standard package in python.
#
DISTANCE_BETWEEN_GREEN_LIGHTS = 20  # meters, distance between lights on ground. I *think* that the standard for taxi cetner line lights is 60 meters.
DISTANCE_BETWEEN_STOPLIGHTS = 2  # meters, distance between red stop lights on the ground.
DISTANCE_BETWEEN_LIGHTS = 40  # meters, when showing all taxiways. This can build numerous lights so keep them far apart!

LIGHTS_AHEAD = 0  # Number of lights in front of rabbit. If 0, lights all lights up to next stopbar or destination.
RABBIT_LENGTH = 10  # number of lights that blink in front of aircraft
RABBIT_DURATION = 0.2  # secs duration of "off" light in rabbit, also determine the rabbit speed

# While FtG is running for your, dim the airport lights to level "off", "lo", "med", or "hi". Other values are ignored.
RUNWAY_LIGHT_LEVEL_WHILE_FTG = "lo" # "off", "lo", "med", or "hi"
# May be RUNWAY_LIGHT_LEVEL_WHILE_FTG float[0, 1]?, xp.setDataf(xp.findDataRef('sim/graphics/scenery/airport_light_level'), 0.75)