# Location for user-defined preference parameters
#
# This template is a list of possible preference parameters.
# Not all parameters iside Follow the greens can be changed, only some of them.
#
# Any of this parameter can be set to a sensible value to affect the behavior of FtG
# Some extreme value may break FtG or even X-Plane.
#
# If a parameter does not appear here, it means it cannot be changed through this file.
#
# Please note that, as TOML format requires it, boolean type parameters true or false
# should be written in all lowercase, true, not True or TRUE.
# It is advisable to quote text strings, like "off".
#
#
# meters, distance between taxiway lights on ground. Float value.
DISTANCE_BETWEEN_GREEN_LIGHTS = 20

# In meters, distance between lights on ground *when showing all taxiways*.
# This can build numerous lights so keep them far apart! Float value.
DISTANCE_BETWEEN_LIGHTS = 40

# Number of lights in front of rabbit. If 0, lights all lights up to next stopbar or destination. Integer value.
LIGHTS_AHEAD = 0


# number of lights that blink in front of aircraft. Integer value.
RABBIT_LENGTH = 10

# secs duration of "off" light in rabbit, also determine the rabbit speed. Float value.
RABBIT_DURATION = 0.2


# While FtG is running for your, dim the airport lights to level "off", "lo", "med", or "hi". Other values are ignored. Default is "lo".
RUNWAY_LIGHT_LEVEL_WHILE_FTG = "off" # "off", "lo", "med", or "hi". Quotes around the word to tell it is a string.


# Strict mode tries to find a route while respecting all constraints like oneway or taxiway width
RESPECT_CONSTRAINTS = false  # true or false, lowercase, no quote around the word

# Standard Python logging levels: (please use indicated value or behavior might be unpredictable.)
# logging.NOTSET = 0
# logging.DEBUG = 10
# logging.INFO = 20
# logging.WARNING = 30
# logging.ERROR = 40
# logging.CRITICAL = 50
LOGGING_LEVEL = 20   # 20 => logger.INFO is default value. 10 => logging.DEBUG might be requested in case of issue.
